# Generated by Django 5.0.2 on 2024-02-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_listing_bundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bundle',
            field=models.ManyToManyField(blank=True, related_name='bundle', to='main.game'),
        ),
    ]
